const equipos=[
{tipo:'Plataforma de tijera',altura:'8 metros',energia:'Eléctrica',img:'https://img.forconstructionpros.com/files/base/acbm/fcp/image/2020/02/Snorkel_S3019E__1_.5e48ad0ee0bab.png?auto=format%2Ccompress&q=70',uso:'Compacta y maniobrable para mantenimiento, instalaciones y trabajos interiores sobre superficies niveladas.'},
{tipo:'Plataforma de tijera',altura:'10 metros',energia:'Eléctrica',img:'https://smartutleie-production.s3.amazonaws.com/images/faesagfagga_1EtQrvU.format-jpeg.height-900.jpg',uso:'Excelente alternativa para bodegas, centros logísticos y mantenimiento industrial con operación silenciosa.'},
{tipo:'Plataforma de tijera',altura:'12 metros',energia:'Eléctrica',img:'https://www.genielift.com/images/default-source/product-images/slab-scissor-lifts/gs-3246.jpg',uso:'Mayor altura de trabajo para montaje, mantenimiento e instalaciones en espacios industriales.'},
{tipo:'Brazo articulado',altura:'12 metros',energia:'Eléctrico',img:'https://www.rjc.sa/uploads/equipment/eq_68b8d08d0e81e.webp',uso:'Alcance vertical y horizontal para acceder a puntos elevados con obstáculos y estructuras intermedias.'},
{tipo:'Brazo articulado',altura:'15 metros',energia:'Eléctrico',img:'https://www.workplatformltd.co.uk/cached-img/containers/assets/product-images/genie-articulating-boom-lift-z60dc/z-60-dc_21-%281%29-min-%281%29.jpg/b95112357c96b09d4d4a216e488763f7/z-60-dc_21-%281%29-min-%281%29.webp',uso:'Acceso flexible para faenas técnicas, montaje y mantenimiento que requieren mayor alcance.'}
];
export default function Home(){return <main>
<header><a className="brand" href="#">EQUIRENTAL</a><nav><a href="#equipos">Equipos</a><a href="#nosotros">Nosotros</a><a href="#contacto">Contacto</a></nav></header>
<section className="hero"><div><span>ARRIENDO DE EQUIPOS EN ALTURA</span><h1>Trabaja en altura con seguridad y eficiencia.</h1><p>Arriendo de plataformas de tijera y brazos articulados 100% eléctricos para obras, mantenimiento, instalaciones y trabajos industriales.</p><div className="actions"><a className="primary" href="#equipos">Ver equipos</a><a className="secondary" href="#contacto">Solicitar cotización</a></div></div></section>
<section className="benefits"><div><b>100% eléctricos</b><span>Sin emisiones directas</span></div><div><b>8 a 15 metros</b><span>Alternativas según tu faena</span></div><div><b>Atención directa</b><span>Asesoría para elegir el equipo</span></div></section>
<section id="equipos"><span className="eyebrow">NUESTRA FLOTA</span><h2>Equipos para trabajo en altura</h2><p className="lead">Selecciona la altura y el tipo de plataforma que necesita tu proyecto.</p><div className="grid">{equipos.map((e,i)=><article key={i}><div className={'machine m'+i}><img src={e.img} alt={`${e.tipo} eléctrica de ${e.altura}`} /><span>{e.tipo==='Plataforma de tijera'?'TIJERA':'ARTICULADA'}</span></div><small>{e.energia}</small><h3>{e.tipo}</h3><strong>Altura de trabajo: {e.altura}</strong><p>{e.uso}</p><a className="quote" href="#contacto">Solicitar cotización</a></article>)}</div></section>
<section id="nosotros" className="why"><span className="eyebrow">EQUIRENTAL</span><h2>Una solución simple para trabajar en altura</h2><p>Equipos eléctricos seleccionados para faenas profesionales, operación silenciosa y trabajos en interiores. Te orientamos según altura, acceso y tipo de trabajo.</p><div className="whygrid"><div><b>01</b><span>Elige el tipo de equipo y altura</span></div><div><b>02</b><span>Indica comuna y fechas de arriendo</span></div><div><b>03</b><span>Recibe una cotización para tu proyecto</span></div></div></section>
<section id="contacto" className="contact"><div><span className="eyebrow">COTIZA TU EQUIPO</span><h2>¿Qué altura necesitas?</h2><p>Indícanos el tipo de trabajo, altura requerida, comuna y fechas estimadas. Te ayudamos a seleccionar el equipo adecuado.</p></div><a className="primary" href="mailto:contacto@equirental.cl">Solicitar cotización</a></section>
<footer><b>EQUIRENTAL</b><span>Arriendo de plataformas eléctricas en Chile</span></footer></main>}