const equipos=[
{tipo:'Plataforma de tijera',altura:'8 metros',energia:'Eléctrica',slug:'tijera-8m',img:'https://img.forconstructionpros.com/files/base/acbm/fcp/image/2020/02/Snorkel_S3019E__1_.5e48ad0ee0bab.png?auto=format%2Ccompress&q=70',uso:'Compacta y maniobrable para mantenimiento, instalaciones y trabajos interiores sobre superficies niveladas.'},
{tipo:'Plataforma de tijera',altura:'10 metros',energia:'Eléctrica',slug:'tijera-10m',img:'https://smartutleie-production.s3.amazonaws.com/images/faesagfagga_1EtQrvU.format-jpeg.height-900.jpg',uso:'Excelente alternativa para bodegas, centros logísticos y mantenimiento industrial con operación silenciosa.'},
{tipo:'Plataforma de tijera',altura:'12 metros',energia:'Eléctrica',slug:'tijera-12m',img:'https://www.genielift.com/images/default-source/product-images/slab-scissor-lifts/gs-3246.jpg',uso:'Mayor altura de trabajo para montaje, mantenimiento e instalaciones en espacios industriales.'},
{tipo:'Brazo articulado',altura:'12 metros',energia:'Eléctrico',slug:'articulada-12m',img:'https://www.rjc.sa/uploads/equipment/eq_68b8d08d0e81e.webp',uso:'Alcance vertical y horizontal para acceder a puntos elevados con obstáculos y estructuras intermedias.'},
{tipo:'Brazo articulado',altura:'16 metros',energia:'Eléctrico',slug:'articulada-16m',img:'https://www.workplatformltd.co.uk/cached-img/containers/assets/product-images/genie-articulating-boom-lift-z60dc/z-60-dc_21-%281%29-min-%281%29.jpg/b95112357c96b09d4d4a216e488763f7/z-60-dc_21-%281%29-min-%281%29.webp',uso:'Acceso flexible para faenas técnicas, montaje y mantenimiento que requieren mayor alcance.'}
];
export default function Home(){return <main>
<header><a className="brand logoBrand" href="#"><img src="/LOGOTIPO.png" alt="EquiRental" /></a><nav><a href="#equipos">Equipos</a><a href="#nosotros">Nosotros</a><a href="#contacto">Contacto</a></nav></header>
<section className="hero heroPropuesta"><a className="heroPropuestaLink" href="#equipos" aria-label="Ver equipos disponibles"><img src="/home-propuesta.png.png" alt="EquiRental - Arriendo de equipos en altura" /></a></section>
<section className="benefits"><div><b>100% eléctricos</b><span>Sin emisiones directas</span></div><div><b>8 a 16 metros</b><span>Alternativas según tu faena</span></div><div><b>Transporte de equipos</b><span>Entrega y retiro coordinados según ubicación</span></div><div><b>Atención directa</b><span>Asesoría para elegir el equipo</span></div></section>
<section id="equipos"><span className="eyebrow">NUESTRA FLOTA</span><h2>Equipos para trabajo en altura</h2><p className="lead">Selecciona la altura y el tipo de plataforma que necesita tu proyecto.</p><div className="grid">{equipos.map((e,i)=><article key={i}><div className={'machine m'+i}><img src={e.img} alt={`${e.tipo} eléctrica de ${e.altura}`} /><span>{e.tipo==='Plataforma de tijera'?'TIJERA':'ARTICULADA'}</span></div><small>{e.energia}</small><h3>{e.tipo}</h3><strong>Altura de trabajo: {e.altura}</strong><p>{e.uso}</p><div className="cardActions"><a className="specLink" href={`/equipos/${e.slug}`}>Ver ficha técnica</a><a className="quote" href="#contacto">Cotizar</a></div></article>)}</div></section>
<section id="nosotros" className="why"><span className="eyebrow">EQUIRENTAL</span><h2>Una solución simple para trabajar en altura</h2><p>Equipos eléctricos seleccionados para faenas profesionales, operación silenciosa y trabajos en interiores. Te orientamos según altura, acceso y tipo de trabajo.</p><div className="whygrid"><div><b>01</b><span>Elige el tipo de equipo y altura</span></div><div><b>02</b><span>Indica comuna y fechas de arriendo</span></div><div><b>03</b><span>Recibe una cotización para tu proyecto</span></div></div></section>
<section id="contacto" className="contact"><div className="contactIntro"><span className="eyebrow">COTIZA TU EQUIPO</span><h2>¿Qué altura necesitas?</h2><p>Cuéntanos sobre tu proyecto y te contactaremos para ayudarte a seleccionar el equipo adecuado.</p><a className="whatsapp" href="https://wa.me/56992247334?text=Hola%20EquiRental%2C%20necesito%20cotizar%20un%20equipo%20para%20trabajo%20en%20altura." target="_blank" rel="noreferrer">Cotizar por WhatsApp</a></div><form className="contactForm" action="mailto:contacto@equirental.cl" method="post" encType="text/plain"><div className="formRow"><label>Nombre<input name="Nombre" required /></label><label>Empresa<input name="Empresa" /></label></div><div className="formRow"><label>Teléfono<input name="Telefono" type="tel" required /></label><label>Email<input name="Email" type="email" required /></label></div><div className="formRow"><label>Tipo de equipo<select name="Equipo" defaultValue=""><option value="" disabled>Seleccionar</option><option>Plataforma de tijera</option><option>Brazo articulado</option></select></label><label>Altura requerida<select name="Altura" defaultValue=""><option value="" disabled>Seleccionar</option><option>8 metros</option><option>10 metros</option><option>12 metros</option><option>16 metros</option></select></label></div><div className="formRow"><label>Comuna<input name="Comuna" /></label><label>Fechas estimadas<input name="Fechas" placeholder="Ej: 5 al 12 de octubre" /></label></div><label>Mensaje<textarea name="Mensaje" rows="4" placeholder="Cuéntanos brevemente sobre el trabajo a realizar"></textarea></label><button className="primary formSubmit" type="submit">Enviar solicitud</button></form></section><a className="whatsappFloat" href="https://wa.me/56992247334?text=Hola%20EquiRental%2C%20necesito%20cotizar%20un%20equipo%20para%20trabajo%20en%20altura." target="_blank" rel="noreferrer" aria-label="Contactar a EquiRental por WhatsApp">WhatsApp</a>
<footer><a className="footerLogo" href="#"><img src="/LOGOTIPO.png" alt="EquiRental" /></a><span>Arriendo de plataformas eléctricas en Chile</span></footer></main>}