export const metadata={title:'Trabajos en Altura con Plataformas Elevadoras | EquiRental',description:'Soluciones con plataformas tijera y brazos articulados para mantenimiento industrial, instalaciones, bodegas, fachadas, climatización y montaje.',alternates:{canonical:'/trabajos'}};
const trabajos=[
['mantenimiento-industrial-altura','Mantenimiento industrial','Inspección, mantenimiento preventivo y correctivo en instalaciones industriales.','/Tijera-01.png','TIJERA · ARTICULADA'],
['instalacion-luminarias-altura','Iluminación en altura','Instalación, recambio y mantenimiento de luminarias en bodegas y galpones.','/Tijera-02.png','TIJERA'],
['trabajos-electricos-altura','Instalaciones eléctricas','Canalizaciones, bandejas, cableado y componentes eléctricos ubicados en altura.','/Tijera-03.png','TIJERA · ARTICULADA'],
['climatizacion-hvac-altura','Climatización y HVAC','Instalación y mantenimiento de ductos, unidades y componentes de climatización.','/brazo-01.png','ARTICULADA'],
['construccion-montaje-altura','Construcción y montaje','Montaje, terminaciones e instalaciones para obras y recintos industriales.','/brazo-02.png','TIJERA · ARTICULADA'],
['mantenimiento-bodegas-centros-logisticos','Bodegas y centros logísticos','Mantenimiento de infraestructura e instalaciones interiores en centros de distribución.','/Tijera-04.png','TIJERA'],
['pintura-terminaciones-altura','Pintura y terminaciones','Acceso elevado para pintura, revestimientos, reparaciones y terminaciones.','/Tijera-05.png','TIJERA · ARTICULADA'],
['instalacion-senaletica-letreros','Señalética y letreros','Montaje, mantenimiento y recambio de señalética y elementos gráficos elevados.','/brazo-04.png','ARTICULADA'],
['mantenimiento-fachadas-altura','Mantenimiento de fachadas','Inspección, sellos, reparaciones y terminaciones en fachadas accesibles.','/brazo-05.png','ARTICULADA'],
['trabajos-altura-con-obstaculos','Acceso con obstáculos','Soluciones para puntos de trabajo detrás o por encima de estructuras y maquinaria.','/brazo-06.png','ARTICULADA']
];
export default function Page(){return <main className="workHub">
<header><a className="brand logoBrand" href="/"><img src="/LOGOTIPO.png" alt="EquiRental" /></a><nav><a href="/">Inicio</a><a href="/#equipos">Equipos</a><a href="/#contacto">Contacto</a></nav></header>
<section className="workHero"><div><span className="workKicker">SOLUCIONES PARA TRABAJOS EN ALTURA</span><h1>Equipos para cada desafío en altura.</h1><p>Plataformas elevadoras eléctricas para mantenimiento, instalaciones, montaje y operación industrial. Seleccionamos la alternativa según altura, acceso y condiciones de la faena.</p><div className="workHeroActions"><a href="#aplicaciones">Explorar aplicaciones</a><a href="/#contacto">Solicitar asesoría</a></div></div><div className="workHeroVisual"><img src="/brazo-01.png" alt="Brazo articulado eléctrico EquiRental" /><div><strong>8–16 m</strong><span>Alturas de trabajo disponibles</span></div></div></section>
<section className="workStats"><div><strong>100%</strong><span>Equipos eléctricos</span></div><div><strong>2</strong><span>Tipos de plataforma</span></div><div><strong>8–16 m</strong><span>Rango de trabajo</span></div><div><strong>RM</strong><span>Atención y coordinación</span></div></section>
<section id="aplicaciones" className="workApplications"><div className="workSectionHead"><div><span>APLICACIONES</span><h2>Soluciones según el tipo de trabajo</h2></div><p>Cada faena presenta condiciones diferentes. Revisa las aplicaciones y conoce qué tipo de plataforma puede adaptarse mejor al trabajo.</p></div><div className="workGrid">{trabajos.map(([slug,titulo,texto,img,tipo],i)=><a className="workCard" href={'/trabajos/'+slug} key={slug}><div className="workCardImage"><img src={img} alt={titulo+' con plataforma elevadora'} /><span>{String(i+1).padStart(2,'0')}</span></div><div className="workCardBody"><small>{tipo}</small><h3>{titulo}</h3><p>{texto}</p><b>Ver solución <span>→</span></b></div></a>)}</div></section>
<section className="workGuide"><div><span>ASESORÍA EQUIRENTAL</span><h2>No se trata solo de la altura.</h2><p>Para seleccionar una plataforma también revisamos acceso, obstáculos, superficie, espacio de maniobra y alcance requerido.</p></div><div className="workGuideSteps"><div><b>01</b><span>Altura y punto de trabajo</span></div><div><b>02</b><span>Accesos y obstáculos</span></div><div><b>03</b><span>Superficie y maniobra</span></div><div><b>04</b><span>Equipo recomendado</span></div></div></section>
<section className="workFinal"><div><span>COTIZACIONES</span><h2>Cuéntanos dónde necesitas trabajar.</h2><p>Indica comuna, altura aproximada y tipo de faena. Te orientamos para seleccionar el equipo.</p></div><a href="https://wa.me/56992247334?text=Hola%20EquiRental%2C%20necesito%20asesoria%20para%20un%20trabajo%20en%20altura." target="_blank" rel="noreferrer">Cotizar por WhatsApp</a></section>
</main>}